version: "3"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    networks:
      - network
    ports:
      - "8000:80"
    depends_on:
      - django

  django:
    image: bellarbab
    build:
      context: .
    volumes:
      - bellarbab-db:/app/database
    networks:
     - network
    expose:
      - "8001"

volumes:
  bellarbab-db:
    external: true

networks:
  network:
    driver: bridge