version: "3"

services:
  server:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    networks:
      - network
    ports:
      - "8000:8000"

  backend:
    image: bellarbab
    build:
      context: .
    volumes:
      - bellarbab-db:/app/database
    networks:
     - network
    ports:
      - "8001:8001"

volumes:
  bellarbab-db:
    external: true

networks:
  network: