version: "3"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    networks:
      - network
    ports:
      - "8000:80"
    depends_on:
      - django

  django:
    image: bellarbab
    pull_policy: never
    build:
      context: .
    environment:
      - DEBUG=FALSE
    volumes:
      - bellarbab-db:/app/database:rw
    networks:
     - network
    expose:
      - "80"

volumes:
  bellarbab-db:
    external: true

networks:
  network:
    driver: bridge