# Generated by Django 4.2.8 on 2023-12-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "mtype",
                    models.CharField(
                        choices=[("B", "breakfast"), ("L", "lunch"), ("D", "dinner")],
                        max_length=1,
                    ),
                ),
                ("content", models.CharField(max_length=300)),
                ("calories", models.IntegerField()),
            ],
        ),
    ]
